### ISSUE TITLE
Functional machine learning - Scala and neural nets

### ISSUE THREAD

**Issue by bradjohns94** [A2FP/a2fp#10]
Still in progress, watch the project: https://GitHub.com/bradjohns94/mnist-from-scratch

URL written on the fly... Hopefully it works

**Comment by filippovitale** [comment]
Brad, I locked this talk to the July meetup:

> **Trend de la Trend**
> _Benefits and Pitfalls for Deep Learning with Functional Programming_
>

**Comment by jpierson** [comment]
I thought this scheduled talk at Strange Loop on [Monadic Deep Learning](https://www.thestrangeloop.com/2017/monadic-deep-learning.html) may be interesting to those who enjoyed this presentation.

**Comment by filippovitale** [comment]
Nice!
