### ISSUE TITLE
Somewhat Functional Programming

### ISSUE THREAD

**Issue by justcolin** [A2FP/a2fp#20]
Functional programming isn’t all about purity, mathematical theory and type systems (despite what Mark may want us to think). FP can be a great asset even in the most mutable of languages. This talk is about how a little FP is practical in the day to day life of a mutable programmer.

30 minutes

**Comment by mwotton** [comment]
Heresy! :)

**Comment by filippovitale** [comment]
Forgive me Backus, for I have mutated – Colin Fulton

No matter what your job is, at some point you will use a mutation-heavy language. Maybe it’s the language you use at work, maybe it’s the scripting language you use for daily tasks, maybe it’s for your build system or tests. This talk is about keep sane and writing good code in an impure world.
