### ISSUE TITLE
proposed talk: regular expressions in haskell 

### ISSUE THREAD

**Issue by gbwey** [A2FP/a2fp#24]
Hi,
I am interested in doing a talk about how to do regular expressions better by utilising haskell parsers.
I'l build the whole library from scratch and then show pragmatic examples of how to use it. This provides type safe, highly composable combinators with error handling. 
The duration of the talk should be around 45mins and I can do it anytime.

Best,
Grant

**Comment by filippovitale** [comment]
That sounds great Grant.

I have checked the venue availability for next week and I was wondering if next week would be good for you to present and which day would work better:
- Tue July, 24
- Wed July, 25
- Thu July, 26

Thanks again for the proposal 👍

**Comment by gbwey** [comment]
Hi Filippo,
Tuesday the 24th is perfect.
Thanks

**Comment by gbwey9** [comment]
Thanks for organizing this. 
Can you let me know if you have a screen I can hook my laptop up to?
I have a usb-c to hdmi cable and a usb-c to display port adaptor if that helps.

**Comment by gbwey9** [comment]
Excellent. See you on Tuesday!
