### ISSUE TITLE
Purescript

### ISSUE THREAD

**Issue by BebeSparkelSparkel** [A2FP/a2fp#26]
@filippovitale Hey Filippo,

I've recently been looking into purescript and have struggled figuring out the ecosystem. Maybe some people would be interested in getting purescript setup on their systems, so I could give a talk on how to get through through some of the pitfalls.

**Comment by filippovitale** [comment]
Would this be a 5-15min lightning talk?

**Comment by BebeSparkelSparkel** [comment]
I think it could be a quick 15 minute talk.

Introduce what purescript is trying to do
pitfalls
go over resources for learning

It would nice to do on the 28th since I'm driving over already for the semigroup talk

**Comment by filippovitale** [comment]
Awesome! I am updating the meetup event.

Thank you and see you on Tuesday August 28th
