### ISSUE TITLE
Functional Pipes in Python

### ISSUE THREAD

**Issue by BebeSparkelSparkel** [A2FP/a2fp#3]
Just starting a new package that is ready for functionality to be added so check it out if you want to be able to chain iterables together check it out.
[https://github.com/BebeSparkelSparkel/functional_pipes](https://github.com/BebeSparkelSparkel/functional_pipes)

Cool Features:
Reuseable use pipes
Multi flow pipes
Easily add new methods to your Pipe

If there is interest in this I would be willing to give a demo at a meeting.

**Comment by filippovitale** [comment]
How long do you think the talk will be? Could eventually be ready for the June meetup?

**Comment by BebeSparkelSparkel** [comment]
I'd say at most 15min without questions

**Comment by BebeSparkelSparkel** [comment]
Hey everyone I just added a README so that should be helpful.

**Comment by BebeSparkelSparkel** [comment]
@filippovitale when do you think that we'll have time to present this?

**Comment by filippovitale** [comment]
Would you be able to present at the meetup next Thursday?

**Comment by WilliamRusnackAtFord** [comment]
I should be able to put together a quick presentation

**Comment by filippovitale** [comment]
I am a little confuse: are both @BebeSparkelSparkel and @WilliamRusnackAtFord your account?

**Comment by filippovitale** [comment]
Name checks out 🦊
