### ISSUE TITLE
proposal for a talk on predicates

### ISSUE THREAD

**Issue by gbwey9** [A2FP/a2fp#31]
Hi,
I am interested in doing a talk about predicates - what they are and how to represent them as a tree.

The problem with predicates is that they come back with True or False but don't tell us what the question was. Most predicate pacakges use composable functions that automatically lose information.

I will introduce a library that alllows you to display and compose complex predicates and be able to trace the complete tree of possibilities. In this way you can see exactly which path of failed predicate(s) caused the issue along with the data at every step of the way.

The duration of the talk is about 45 minutes and I can do it anytime.
Thanks.

**Comment by filippovitale** [comment]
slides are up: https://github.com/A2FP/a2fp/tree/master/slides/2018-10-30%20meetup
