### ISSUE TITLE
Intro to the Haskell "lens" library

### ISSUE THREAD

**Issue by jasonstolaruk** [A2FP/a2fp#5]
A brief introduction to the popular [lens](https://hackage.haskell.org/package/lens) library. Motivation and illustrations of practical applications. Benefits and disadvantages (there are plenty of both).
I would mention in passing that the library was conceived and constructed based on deep abstractions, but I wouldn't attempt to explain them.
This talk would be about 45 mins long including questions.

**Comment by filippovitale** [comment]
Are you willing to present on Thu Aug 31?

**Comment by jasonstolaruk** [comment]
@filippovitale Sorry for the late reply. Yes I can do that. About lens, right? How long should the presentation be?

**Comment by filippovitale** [comment]
We tend to have 2 presentations at every meetup, a short one (5-15min) and a main one (30-40min) but of course we can adapt!

Which format you had in mind? According to your initial description the ~40min, right?

**Comment by jasonstolaruk** [comment]
Well I think the presentation would work in the 15 min time slot as well. So I can do either one.

**Comment by mwotton** [comment]
@jasonstolaruk you take the long talk.

**Comment by jasonstolaruk** [comment]
@mwotton OK, sounds good!

**Comment by filippovitale** [comment]
So @jasonstolaruk , is it confirmed for the Aug-31 meetup?

**Comment by jasonstolaruk** [comment]
@filippovitale Yep we're good. I'll be there!
