### ISSUE TITLE
Practical Haskell Web Apps

### ISSUE THREAD

**Issue by mwotton** [A2FP/a2fp#7]
a quick overview of what a web app looks like in Haskell, typical patterns of handling databases & input fomats & content types etc.

**Comment by filippovitale** [comment]
Are you willing to present on Thu Aug 31?

**Comment by mwotton** [comment]
Yep.

**Comment by filippovitale** [comment]
Would you prefer a short 5-15min or longer 3-40min preso?

Let's give priority to: https://github.com/A2FP/a2fp/issues/5

**Comment by mwotton** [comment]
I can do either. 15 minutes will be a whistle-stop tour, but that's fine.

**Comment by filippovitale** [comment]
If you prefer make this talk a longer one, I could easily make a 10-15 talk about https://github.com/A2FP/a2fp/issues/14

**Comment by mwotton** [comment]
sure, i'll talk a little longer.

**Comment by filippovitale** [comment]
BTW https://twitter.com/alexeyzab/status/895279169323618304/photo/1

**Comment by mwotton** [comment]
Hehe. I saw that one - not a bad title though.

**Comment by mwotton** [comment]
nb. @snoyberg talk I mentioned is available at https://www.snoyman.com/reveal/conduit-yesod#/
